create table feature_flag (
    id uuid primary key,
    flag_key varchar(64) not null unique,
    description varchar(512),
    enabled boolean not null default false,
    rollout_percentage integer not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint chk_feature_flag_key_lower check (flag_key = lower(flag_key)),
    constraint chk_feature_flag_rollout_percentage check (rollout_percentage between 0 and 100)
);

create table feature_flag_target_user (
    feature_flag_id uuid not null,
    target_user_id varchar(255) not null,
    primary key (feature_flag_id, target_user_id),
    constraint fk_feature_flag_target_user_flag foreign key (feature_flag_id) references feature_flag(id) on delete cascade
);

create table evaluation_log (
    id bigint generated by default as identity primary key,
    flag_key varchar(64) not null,
    user_id varchar(255) not null,
    result boolean not null,
    reason varchar(64) not null,
    evaluated_at timestamp with time zone not null
);

create index idx_evaluation_log_flag_key on evaluation_log(flag_key);
create index idx_evaluation_log_user_id on evaluation_log(user_id);
create index idx_evaluation_log_evaluated_at on evaluation_log(evaluated_at);
